### ISSUE TITLE
Crear archivo con datos de artistas

### ISSUE THREAD

**Issue by pyjavo** [mj161099/spotipy#1]
De la forma como está planteado, el código de python crecerá al igual que los datos. Se debe separar la lógica de los datos (ejemplo: la información de Luis fonsi puede estar en un JSON o un diccionario, en vez de ser una clase).

**Comment by mj161099** [comment]
El problema donde el código crecerá al igual que los datos ha sido resuelto en el commit  #[081016e](https://github.com/mj161099/spotipy/commit/081016edb5816e850cc82da2e2b19a5566ccc6c6). Ahora el sistema maneja los datos de los artistas mediante un archivo de formato JSON separando la lógica de los datos. Gracias por tu colaboración!

**Comment by mj161099** [comment]
El problema donde el código crecerá al igual que los datos ha sido resuelto en el commit  #[081016e](https://github.com/mj161099/spotipy/commit/081016edb5816e850cc82da2e2b19a5566ccc6c6). Ahora el sistema maneja los datos de los artistas mediante un archivo de formato JSON separando la lógica de los datos. Gracias por tu colaboración!
